# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-10-29T16-01-48Z
  command: server --console-address ":9001" /mnt/data
  ports:
    - "9000:9000"  # API port
    - "9001:9001"  # Console port
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  minio:
    <<: *minio-common
    volumes:
      - ${MINIO_S3_LOCAL_STORAGE}:/mnt/data



